[package]
name = "cargo-fly"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/alxpettit/cargo-fly"
tags = ["blazingly_fast", "memes", "cli", "cargo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
